name: Testes de Integração Staging

on:
  push:
    branches:
      - develop

jobs:
  integrar-staging:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do repositório
        uses: actions/checkout@v3

      - name: 🧱 Subir backend IA em staging
        run: |
          docker compose -f docker-compose.staging.yml up -d backend_ia-staging
          sleep 10

      - name: 🧪 Testar endpoint FastAPI (/docs)
        run: |
          curl --fail http://localhost:5001/docs || exit 1

      - name: 📦 Instalar dependências do frontend
        working-directory: ./frontend
        run: |
          npm install

      - name: 🧪 Compilar frontend com Vite
        working-directory: ./frontend
        run: |
          npm run build

      - name: ✅ Integração validada com sucesso
        run: echo "Frontend compilado e backend IA responde corretamente"
